# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\theGUI.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(989, 750)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.TabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.TabWidget.setGeometry(QtCore.QRect(20, 70, 861, 561))
        self.TabWidget.setObjectName("TabWidget")
        self.TabStatus = QtWidgets.QWidget()
        self.TabStatus.setObjectName("TabStatus")
        self.gridLayoutWidget = QtWidgets.QWidget(self.TabStatus)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 19, 571, 411))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.LabelH2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LabelH2.setObjectName("LabelH2")
        self.gridLayout.addWidget(self.LabelH2, 2, 5, 1, 1)
        self.VariablePress4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.VariablePress4.setObjectName("VariablePress4")
        self.gridLayout.addWidget(self.VariablePress4, 4, 4, 1, 1)
        self.LabelPress3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LabelPress3.setObjectName("LabelPress3")
        self.gridLayout.addWidget(self.LabelPress3, 3, 3, 1, 1)
        self.LabelH1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LabelH1.setObjectName("LabelH1")
        self.gridLayout.addWidget(self.LabelH1, 1, 5, 1, 1)
        self.LabelPress4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LabelPress4.setObjectName("LabelPress4")
        self.gridLayout.addWidget(self.LabelPress4, 4, 3, 1, 1)
        self.LabelPress1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LabelPress1.setObjectName("LabelPress1")
        self.gridLayout.addWidget(self.LabelPress1, 1, 3, 1, 1)
        self.LabelT2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LabelT2.setObjectName("LabelT2")
        self.gridLayout.addWidget(self.LabelT2, 2, 1, 1, 1)
        self.HeaderPressure = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.HeaderPressure.setFont(font)
        self.HeaderPressure.setLineWidth(1)
        self.HeaderPressure.setObjectName("HeaderPressure")
        self.gridLayout.addWidget(self.HeaderPressure, 0, 3, 1, 2, QtCore.Qt.AlignHCenter)
        self.VariablePress2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.VariablePress2.setObjectName("VariablePress2")
        self.gridLayout.addWidget(self.VariablePress2, 2, 4, 1, 1)
        self.LabelPump3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LabelPump3.setObjectName("LabelPump3")
        self.gridLayout.addWidget(self.LabelPump3, 7, 5, 1, 1)
        self.LabelPump2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LabelPump2.setObjectName("LabelPump2")
        self.gridLayout.addWidget(self.LabelPump2, 6, 5, 1, 1)
        self.VariableT3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.VariableT3.setObjectName("VariableT3")
        self.gridLayout.addWidget(self.VariableT3, 3, 2, 1, 1)
        self.HeaderTemperature = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.HeaderTemperature.setFont(font)
        self.HeaderTemperature.setLineWidth(1)
        self.HeaderTemperature.setObjectName("HeaderTemperature")
        self.gridLayout.addWidget(self.HeaderTemperature, 0, 1, 1, 2, QtCore.Qt.AlignHCenter)
        self.VariablePress1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.VariablePress1.setObjectName("VariablePress1")
        self.gridLayout.addWidget(self.VariablePress1, 1, 4, 1, 1)
        self.VariableT1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.VariableT1.setObjectName("VariableT1")
        self.gridLayout.addWidget(self.VariableT1, 1, 2, 1, 1)
        self.LabelT1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LabelT1.setAutoFillBackground(True)
        self.LabelT1.setObjectName("LabelT1")
        self.gridLayout.addWidget(self.LabelT1, 1, 1, 1, 1)
        self.LabelPump1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LabelPump1.setObjectName("LabelPump1")
        self.gridLayout.addWidget(self.LabelPump1, 5, 5, 1, 1)
        self.LabelT3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LabelT3.setObjectName("LabelT3")
        self.gridLayout.addWidget(self.LabelT3, 3, 1, 1, 1)
        self.LabelT9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LabelT9.setObjectName("LabelT9")
        self.gridLayout.addWidget(self.LabelT9, 9, 1, 1, 1)
        self.LabelH3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LabelH3.setObjectName("LabelH3")
        self.gridLayout.addWidget(self.LabelH3, 3, 5, 1, 1)
        self.LabelPress2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LabelPress2.setObjectName("LabelPress2")
        self.gridLayout.addWidget(self.LabelPress2, 2, 3, 1, 1)
        self.VariableT8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.VariableT8.setObjectName("VariableT8")
        self.gridLayout.addWidget(self.VariableT8, 8, 2, 1, 1)
        self.LabelT6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LabelT6.setObjectName("LabelT6")
        self.gridLayout.addWidget(self.LabelT6, 6, 1, 1, 1)
        self.LabelT7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LabelT7.setObjectName("LabelT7")
        self.gridLayout.addWidget(self.LabelT7, 7, 1, 1, 1)
        self.VariableT6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.VariableT6.setObjectName("VariableT6")
        self.gridLayout.addWidget(self.VariableT6, 6, 2, 1, 1)
        self.LabelT8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LabelT8.setObjectName("LabelT8")
        self.gridLayout.addWidget(self.LabelT8, 8, 1, 1, 1)
        self.VariableT7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.VariableT7.setObjectName("VariableT7")
        self.gridLayout.addWidget(self.VariableT7, 7, 2, 1, 1)
        self.VariableT2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.VariableT2.setObjectName("VariableT2")
        self.gridLayout.addWidget(self.VariableT2, 2, 2, 1, 1)
        self.LabelT4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LabelT4.setObjectName("LabelT4")
        self.gridLayout.addWidget(self.LabelT4, 4, 1, 1, 1)
        self.VariableT9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.VariableT9.setObjectName("VariableT9")
        self.gridLayout.addWidget(self.VariableT9, 9, 2, 1, 1)
        self.VariableT4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.VariableT4.setObjectName("VariableT4")
        self.gridLayout.addWidget(self.VariableT4, 4, 2, 1, 1)
        self.VariablePress3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.VariablePress3.setObjectName("VariablePress3")
        self.gridLayout.addWidget(self.VariablePress3, 3, 4, 1, 1)
        self.LabelT5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LabelT5.setObjectName("LabelT5")
        self.gridLayout.addWidget(self.LabelT5, 5, 1, 1, 1)
        self.VariableT5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.VariableT5.setObjectName("VariableT5")
        self.gridLayout.addWidget(self.VariableT5, 5, 2, 1, 1)
        self.VariableH1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.VariableH1.setObjectName("VariableH1")
        self.gridLayout.addWidget(self.VariableH1, 1, 6, 1, 1)
        self.HeaderController = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.HeaderController.setFont(font)
        self.HeaderController.setObjectName("HeaderController")
        self.gridLayout.addWidget(self.HeaderController, 0, 5, 1, 2, QtCore.Qt.AlignHCenter)
        self.VariableH2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.VariableH2.setObjectName("VariableH2")
        self.gridLayout.addWidget(self.VariableH2, 2, 6, 1, 1)
        self.VariableH3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.VariableH3.setObjectName("VariableH3")
        self.gridLayout.addWidget(self.VariableH3, 3, 6, 1, 1)
        self.VariablePump1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.VariablePump1.setObjectName("VariablePump1")
        self.gridLayout.addWidget(self.VariablePump1, 5, 6, 1, 1)
        self.VariablePump2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.VariablePump2.setObjectName("VariablePump2")
        self.gridLayout.addWidget(self.VariablePump2, 6, 6, 1, 1)
        self.VariablePump3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.VariablePump3.setObjectName("VariablePump3")
        self.gridLayout.addWidget(self.VariablePump3, 7, 6, 1, 1)
        self.TabWidget.addTab(self.TabStatus, "")
        self.TabHeater1 = QtWidgets.QWidget()
        self.TabHeater1.setObjectName("TabHeater1")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.TabHeater1)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 531, 232))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.LabelHeaterStatus = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.LabelHeaterStatus.setObjectName("LabelHeaterStatus")
        self.gridLayout_2.addWidget(self.LabelHeaterStatus, 2, 0, 1, 1)
        self.LabelHeater1Temp = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.LabelHeater1Temp.setObjectName("LabelHeater1Temp")
        self.gridLayout_2.addWidget(self.LabelHeater1Temp, 1, 0, 1, 1)
        self.VariableHeater1Temp = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.VariableHeater1Temp.setObjectName("VariableHeater1Temp")
        self.gridLayout_2.addWidget(self.VariableHeater1Temp, 1, 1, 1, 1)
        self.VariableHeater1Status = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.VariableHeater1Status.setObjectName("VariableHeater1Status")
        self.gridLayout_2.addWidget(self.VariableHeater1Status, 2, 1, 1, 1)
        self.ButtonUpdateHeater1Setpoint = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.ButtonUpdateHeater1Setpoint.setObjectName("ButtonUpdateHeater1Setpoint")
        self.gridLayout_2.addWidget(self.ButtonUpdateHeater1Setpoint, 3, 3, 1, 1)
        self.VariableHeater1Setpoint = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.VariableHeater1Setpoint.setObjectName("VariableHeater1Setpoint")
        self.gridLayout_2.addWidget(self.VariableHeater1Setpoint, 3, 1, 1, 1)
        self.LabelHeater1MaxTemp = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.LabelHeater1MaxTemp.setObjectName("LabelHeater1MaxTemp")
        self.gridLayout_2.addWidget(self.LabelHeater1MaxTemp, 4, 0, 1, 1)
        self.VariableHeater1MaxTemp = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.VariableHeater1MaxTemp.setObjectName("VariableHeater1MaxTemp")
        self.gridLayout_2.addWidget(self.VariableHeater1MaxTemp, 4, 1, 1, 1)
        self.LabelHeaterSetpointName = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.LabelHeaterSetpointName.setObjectName("LabelHeaterSetpointName")
        self.gridLayout_2.addWidget(self.LabelHeaterSetpointName, 3, 0, 1, 1)
        self.InputHeater1MaxTemp = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.InputHeater1MaxTemp.setObjectName("InputHeater1MaxTemp")
        self.gridLayout_2.addWidget(self.InputHeater1MaxTemp, 4, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.HeaderDesiredValue = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.HeaderDesiredValue.setFont(font)
        self.HeaderDesiredValue.setAlignment(QtCore.Qt.AlignCenter)
        self.HeaderDesiredValue.setObjectName("HeaderDesiredValue")
        self.gridLayout_2.addWidget(self.HeaderDesiredValue, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.ButtonUpdateHeater1MaxTemp = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.ButtonUpdateHeater1MaxTemp.setObjectName("ButtonUpdateHeater1MaxTemp")
        self.gridLayout_2.addWidget(self.ButtonUpdateHeater1MaxTemp, 4, 3, 1, 1)
        self.InputHeater1Setpoint = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.InputHeater1Setpoint.setObjectName("InputHeater1Setpoint")
        self.gridLayout_2.addWidget(self.InputHeater1Setpoint, 3, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.HeaderDesiredValue_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.HeaderDesiredValue_2.setFont(font)
        self.HeaderDesiredValue_2.setAlignment(QtCore.Qt.AlignCenter)
        self.HeaderDesiredValue_2.setObjectName("HeaderDesiredValue_2")
        self.gridLayout_2.addWidget(self.HeaderDesiredValue_2, 0, 3, 1, 1)
        self.TabWidget.addTab(self.TabHeater1, "")
        self.TabHeater2 = QtWidgets.QWidget()
        self.TabHeater2.setObjectName("TabHeater2")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.TabHeater2)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 10, 531, 232))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.LabelHeater2Status = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.LabelHeater2Status.setObjectName("LabelHeater2Status")
        self.gridLayout_3.addWidget(self.LabelHeater2Status, 2, 0, 1, 1)
        self.LabelHeater2Temp = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.LabelHeater2Temp.setObjectName("LabelHeater2Temp")
        self.gridLayout_3.addWidget(self.LabelHeater2Temp, 1, 0, 1, 1)
        self.VariableHeater2Temp = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.VariableHeater2Temp.setObjectName("VariableHeater2Temp")
        self.gridLayout_3.addWidget(self.VariableHeater2Temp, 1, 1, 1, 1)
        self.VariableHeater2Status = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.VariableHeater2Status.setObjectName("VariableHeater2Status")
        self.gridLayout_3.addWidget(self.VariableHeater2Status, 2, 1, 1, 1)
        self.ButtonUpdateHeater2Setpoint = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.ButtonUpdateHeater2Setpoint.setObjectName("ButtonUpdateHeater2Setpoint")
        self.gridLayout_3.addWidget(self.ButtonUpdateHeater2Setpoint, 3, 3, 1, 1)
        self.VariableHeater2Setpoint = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.VariableHeater2Setpoint.setObjectName("VariableHeater2Setpoint")
        self.gridLayout_3.addWidget(self.VariableHeater2Setpoint, 3, 1, 1, 1)
        self.LabelHeater2MaxTemp = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.LabelHeater2MaxTemp.setObjectName("LabelHeater2MaxTemp")
        self.gridLayout_3.addWidget(self.LabelHeater2MaxTemp, 4, 0, 1, 1)
        self.VariableHeater2MaxTemp = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.VariableHeater2MaxTemp.setObjectName("VariableHeater2MaxTemp")
        self.gridLayout_3.addWidget(self.VariableHeater2MaxTemp, 4, 1, 1, 1)
        self.LabelHeater2SetpointName = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.LabelHeater2SetpointName.setObjectName("LabelHeater2SetpointName")
        self.gridLayout_3.addWidget(self.LabelHeater2SetpointName, 3, 0, 1, 1)
        self.InputHeater2MaxTemp = QtWidgets.QTextEdit(self.gridLayoutWidget_3)
        self.InputHeater2MaxTemp.setObjectName("InputHeater2MaxTemp")
        self.gridLayout_3.addWidget(self.InputHeater2MaxTemp, 4, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.HeaderDesiredValue_3 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.HeaderDesiredValue_3.setFont(font)
        self.HeaderDesiredValue_3.setAlignment(QtCore.Qt.AlignCenter)
        self.HeaderDesiredValue_3.setObjectName("HeaderDesiredValue_3")
        self.gridLayout_3.addWidget(self.HeaderDesiredValue_3, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.ButtonUpdateHeater2MaxTemp = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.ButtonUpdateHeater2MaxTemp.setObjectName("ButtonUpdateHeater2MaxTemp")
        self.gridLayout_3.addWidget(self.ButtonUpdateHeater2MaxTemp, 4, 3, 1, 1)
        self.InputHeater2Setpoint = QtWidgets.QTextEdit(self.gridLayoutWidget_3)
        self.InputHeater2Setpoint.setObjectName("InputHeater2Setpoint")
        self.gridLayout_3.addWidget(self.InputHeater2Setpoint, 3, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.HeaderDesiredValue_4 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.HeaderDesiredValue_4.setFont(font)
        self.HeaderDesiredValue_4.setAlignment(QtCore.Qt.AlignCenter)
        self.HeaderDesiredValue_4.setObjectName("HeaderDesiredValue_4")
        self.gridLayout_3.addWidget(self.HeaderDesiredValue_4, 0, 3, 1, 1)
        self.TabWidget.addTab(self.TabHeater2, "")
        self.TabHeater3 = QtWidgets.QWidget()
        self.TabHeater3.setObjectName("TabHeater3")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.TabHeater3)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(0, 10, 531, 232))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.LabelHeater3Status = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.LabelHeater3Status.setObjectName("LabelHeater3Status")
        self.gridLayout_4.addWidget(self.LabelHeater3Status, 2, 0, 1, 1)
        self.LabelHeater3Temp = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.LabelHeater3Temp.setObjectName("LabelHeater3Temp")
        self.gridLayout_4.addWidget(self.LabelHeater3Temp, 1, 0, 1, 1)
        self.VariableHeater3Temp = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.VariableHeater3Temp.setObjectName("VariableHeater3Temp")
        self.gridLayout_4.addWidget(self.VariableHeater3Temp, 1, 1, 1, 1)
        self.VariableHeater3Status = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.VariableHeater3Status.setObjectName("VariableHeater3Status")
        self.gridLayout_4.addWidget(self.VariableHeater3Status, 2, 1, 1, 1)
        self.ButtonUpdateHeater3Setpoint = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.ButtonUpdateHeater3Setpoint.setObjectName("ButtonUpdateHeater3Setpoint")
        self.gridLayout_4.addWidget(self.ButtonUpdateHeater3Setpoint, 3, 3, 1, 1)
        self.VariableHeater3Setpoint = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.VariableHeater3Setpoint.setObjectName("VariableHeater3Setpoint")
        self.gridLayout_4.addWidget(self.VariableHeater3Setpoint, 3, 1, 1, 1)
        self.LabelHeater3MaxTemp = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.LabelHeater3MaxTemp.setObjectName("LabelHeater3MaxTemp")
        self.gridLayout_4.addWidget(self.LabelHeater3MaxTemp, 4, 0, 1, 1)
        self.VariableHeater3MaxTemp = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.VariableHeater3MaxTemp.setObjectName("VariableHeater3MaxTemp")
        self.gridLayout_4.addWidget(self.VariableHeater3MaxTemp, 4, 1, 1, 1)
        self.LabelHeater3SetpointName = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.LabelHeater3SetpointName.setObjectName("LabelHeater3SetpointName")
        self.gridLayout_4.addWidget(self.LabelHeater3SetpointName, 3, 0, 1, 1)
        self.InputHeater3MaxTemp = QtWidgets.QTextEdit(self.gridLayoutWidget_4)
        self.InputHeater3MaxTemp.setObjectName("InputHeater3MaxTemp")
        self.gridLayout_4.addWidget(self.InputHeater3MaxTemp, 4, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.HeaderDesiredValue_5 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.HeaderDesiredValue_5.setFont(font)
        self.HeaderDesiredValue_5.setAlignment(QtCore.Qt.AlignCenter)
        self.HeaderDesiredValue_5.setObjectName("HeaderDesiredValue_5")
        self.gridLayout_4.addWidget(self.HeaderDesiredValue_5, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.ButtonUpdateHeater3MaxTemp = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.ButtonUpdateHeater3MaxTemp.setObjectName("ButtonUpdateHeater3MaxTemp")
        self.gridLayout_4.addWidget(self.ButtonUpdateHeater3MaxTemp, 4, 3, 1, 1)
        self.InputHeater3Setpoint = QtWidgets.QTextEdit(self.gridLayoutWidget_4)
        self.InputHeater3Setpoint.setObjectName("InputHeater3Setpoint")
        self.gridLayout_4.addWidget(self.InputHeater3Setpoint, 3, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.HeaderDesiredValue_6 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.HeaderDesiredValue_6.setFont(font)
        self.HeaderDesiredValue_6.setAlignment(QtCore.Qt.AlignCenter)
        self.HeaderDesiredValue_6.setObjectName("HeaderDesiredValue_6")
        self.gridLayout_4.addWidget(self.HeaderDesiredValue_6, 0, 3, 1, 1)
        self.TabWidget.addTab(self.TabHeater3, "")
        self.TabPump1 = QtWidgets.QWidget()
        self.TabPump1.setEnabled(True)
        self.TabPump1.setAccessibleName("")
        self.TabPump1.setObjectName("TabPump1")
        self.TabWidget.addTab(self.TabPump1, "")
        self.TabPump2 = QtWidgets.QWidget()
        self.TabPump2.setObjectName("TabPump2")
        self.TabWidget.addTab(self.TabPump2, "")
        self.serialLabel = QtWidgets.QLabel(self.centralwidget)
        self.serialLabel.setGeometry(QtCore.QRect(20, 20, 202, 23))
        self.serialLabel.setObjectName("serialLabel")
        self.Button_startSerial = QtWidgets.QPushButton(self.centralwidget)
        self.Button_startSerial.setGeometry(QtCore.QRect(240, 20, 409, 23))
        self.Button_startSerial.setObjectName("Button_startSerial")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 989, 21))
        self.menubar.setObjectName("menubar")
        self.menuWelcome_to_the_CCBC_Brewery = QtWidgets.QMenu(self.menubar)
        self.menuWelcome_to_the_CCBC_Brewery.setObjectName("menuWelcome_to_the_CCBC_Brewery")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuWelcome_to_the_CCBC_Brewery.menuAction())

        self.retranslateUi(MainWindow)
        self.TabWidget.setCurrentIndex(2)
        self.Button_startSerial.clicked.connect(MainWindow.update)
        self.ButtonUpdateHeater1Setpoint.clicked.connect(MainWindow.update)
        self.ButtonUpdateHeater1MaxTemp.clicked.connect(MainWindow.update)
        self.ButtonUpdateHeater2Setpoint.clicked.connect(MainWindow.update)
        self.ButtonUpdateHeater2MaxTemp.clicked.connect(MainWindow.update)
        self.ButtonUpdateHeater3Setpoint.clicked.connect(MainWindow.update)
        self.ButtonUpdateHeater3MaxTemp.clicked.connect(MainWindow.update)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.LabelH2.setText(_translate("MainWindow", "LabelH2"))
        self.VariablePress4.setText(_translate("MainWindow", "VariablePress4"))
        self.LabelPress3.setText(_translate("MainWindow", "LabelPress3"))
        self.LabelH1.setText(_translate("MainWindow", "LabelH1"))
        self.LabelPress4.setText(_translate("MainWindow", "LabelPress4"))
        self.LabelPress1.setText(_translate("MainWindow", "LabelPress1"))
        self.LabelT2.setText(_translate("MainWindow", "LabelT2"))
        self.HeaderPressure.setText(_translate("MainWindow", "Pressures"))
        self.VariablePress2.setText(_translate("MainWindow", "VariablePress2"))
        self.LabelPump3.setText(_translate("MainWindow", "LabelPump3"))
        self.LabelPump2.setText(_translate("MainWindow", "LabelPump2"))
        self.VariableT3.setText(_translate("MainWindow", "VariableT3"))
        self.HeaderTemperature.setText(_translate("MainWindow", "Temperatures (F)"))
        self.VariablePress1.setText(_translate("MainWindow", "VariablePress1"))
        self.VariableT1.setText(_translate("MainWindow", "VariableT1"))
        self.LabelT1.setText(_translate("MainWindow", "LabelT1"))
        self.LabelPump1.setText(_translate("MainWindow", "LabelPump1"))
        self.LabelT3.setText(_translate("MainWindow", "LabelT3"))
        self.LabelT9.setText(_translate("MainWindow", "LabelT9"))
        self.LabelH3.setText(_translate("MainWindow", "LabelH3"))
        self.LabelPress2.setText(_translate("MainWindow", "LabelPress2"))
        self.VariableT8.setText(_translate("MainWindow", "VariableT8"))
        self.LabelT6.setText(_translate("MainWindow", "LabelT6"))
        self.LabelT7.setText(_translate("MainWindow", "LabelT7"))
        self.VariableT6.setText(_translate("MainWindow", "VariableT6"))
        self.LabelT8.setText(_translate("MainWindow", "LabelT8"))
        self.VariableT7.setText(_translate("MainWindow", "VariableT7"))
        self.VariableT2.setText(_translate("MainWindow", "VariableT2"))
        self.LabelT4.setText(_translate("MainWindow", "LabelT4"))
        self.VariableT9.setText(_translate("MainWindow", "VariableT9"))
        self.VariableT4.setText(_translate("MainWindow", "VariableT4"))
        self.VariablePress3.setText(_translate("MainWindow", "VariablePress3"))
        self.LabelT5.setText(_translate("MainWindow", "LabelT5"))
        self.VariableT5.setText(_translate("MainWindow", "VariableT5"))
        self.VariableH1.setText(_translate("MainWindow", "VariableH1"))
        self.HeaderController.setText(_translate("MainWindow", "Controller Statuses"))
        self.VariableH2.setText(_translate("MainWindow", "VariableH2"))
        self.VariableH3.setText(_translate("MainWindow", "VariableH3"))
        self.VariablePump1.setText(_translate("MainWindow", "VariablePump1"))
        self.VariablePump2.setText(_translate("MainWindow", "VaraiblePump2"))
        self.VariablePump3.setText(_translate("MainWindow", "VariablePump3"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.TabStatus), _translate("MainWindow", "Status"))
        self.LabelHeaterStatus.setText(_translate("MainWindow", "Heater Status"))
        self.LabelHeater1Temp.setText(_translate("MainWindow", "Temperature"))
        self.VariableHeater1Temp.setText(_translate("MainWindow", "VariableHeater1Temp"))
        self.VariableHeater1Status.setText(_translate("MainWindow", "VariableHeater1Status"))
        self.ButtonUpdateHeater1Setpoint.setText(_translate("MainWindow", "Update Heater \n"
"1 Setpoint"))
        self.VariableHeater1Setpoint.setText(_translate("MainWindow", "VaraibleHeater1Setpoint"))
        self.LabelHeater1MaxTemp.setText(_translate("MainWindow", "Max Temperature Allowed"))
        self.VariableHeater1MaxTemp.setText(_translate("MainWindow", "VariableHeater1MaxTemp"))
        self.LabelHeaterSetpointName.setText(_translate("MainWindow", "Heater Setpoint"))
        self.HeaderDesiredValue.setText(_translate("MainWindow", "Desired Value \n"
"(input)"))
        self.ButtonUpdateHeater1MaxTemp.setText(_translate("MainWindow", "Update Max \n"
"Temp Setpoint"))
        self.HeaderDesiredValue_2.setText(_translate("MainWindow", "Push Button"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.TabHeater1), _translate("MainWindow", "Heater 1"))
        self.LabelHeater2Status.setText(_translate("MainWindow", "Heater Status"))
        self.LabelHeater2Temp.setText(_translate("MainWindow", "Temperature"))
        self.VariableHeater2Temp.setText(_translate("MainWindow", "VariableHeater2Temp"))
        self.VariableHeater2Status.setText(_translate("MainWindow", "VariableHeater2Status"))
        self.ButtonUpdateHeater2Setpoint.setText(_translate("MainWindow", "Update Heater \n"
"2 Setpoint"))
        self.VariableHeater2Setpoint.setText(_translate("MainWindow", "VaraibleHeater2Setpoint"))
        self.LabelHeater2MaxTemp.setText(_translate("MainWindow", "Max Temperature Allowed"))
        self.VariableHeater2MaxTemp.setText(_translate("MainWindow", "VariableHeater2MaxTemp"))
        self.LabelHeater2SetpointName.setText(_translate("MainWindow", "Heater Setpoint"))
        self.HeaderDesiredValue_3.setText(_translate("MainWindow", "Desired Value \n"
"(input)"))
        self.ButtonUpdateHeater2MaxTemp.setText(_translate("MainWindow", "Update Max \n"
"Temp Setpoint"))
        self.HeaderDesiredValue_4.setText(_translate("MainWindow", "Push Button"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.TabHeater2), _translate("MainWindow", "Heater 2"))
        self.LabelHeater3Status.setText(_translate("MainWindow", "Heater Status"))
        self.LabelHeater3Temp.setText(_translate("MainWindow", "Temperature"))
        self.VariableHeater3Temp.setText(_translate("MainWindow", "VariableHeater3Temp"))
        self.VariableHeater3Status.setText(_translate("MainWindow", "VariableHeater3Status"))
        self.ButtonUpdateHeater3Setpoint.setText(_translate("MainWindow", "Update Heater \n"
"3 Setpoint"))
        self.VariableHeater3Setpoint.setText(_translate("MainWindow", "VaraibleHeater3Setpoint"))
        self.LabelHeater3MaxTemp.setText(_translate("MainWindow", "Max Temperature Allowed"))
        self.VariableHeater3MaxTemp.setText(_translate("MainWindow", "VariableHeater3MaxTemp"))
        self.LabelHeater3SetpointName.setText(_translate("MainWindow", "Heater Setpoint"))
        self.HeaderDesiredValue_5.setText(_translate("MainWindow", "Desired Value \n"
"(input)"))
        self.ButtonUpdateHeater3MaxTemp.setText(_translate("MainWindow", "Update Max \n"
"Temp Setpoint"))
        self.HeaderDesiredValue_6.setText(_translate("MainWindow", "Push Button"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.TabHeater3), _translate("MainWindow", "Heater 3"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.TabPump1), _translate("MainWindow", "Pump1"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.TabPump2), _translate("MainWindow", "Pump2"))
        self.serialLabel.setText(_translate("MainWindow", "SerialLabel"))
        self.Button_startSerial.setText(_translate("MainWindow", "Push to Start Serial Connection"))
        self.menuWelcome_to_the_CCBC_Brewery.setTitle(_translate("MainWindow", "Welcome to the CCBC Brewery!"))

