# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\breweryGUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1030, 779)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.Tabs.setGeometry(QtCore.QRect(20, 160, 961, 581))
        self.Tabs.setObjectName("Tabs")
        self.TabOperations = QtWidgets.QWidget()
        self.TabOperations.setObjectName("TabOperations")
        self.StartTimeLabel = QtWidgets.QLabel(self.TabOperations)
        self.StartTimeLabel.setGeometry(QtCore.QRect(60, 60, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.StartTimeLabel.setFont(font)
        self.StartTimeLabel.setObjectName("StartTimeLabel")
        self.StartNowButton = QtWidgets.QPushButton(self.TabOperations)
        self.StartNowButton.setGeometry(QtCore.QRect(80, 130, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.StartNowButton.setFont(font)
        self.StartNowButton.setObjectName("StartNowButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.TabOperations)
        self.pushButton_2.setGeometry(QtCore.QRect(240, 130, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.start_time_edit = QtWidgets.QDateTimeEdit(self.TabOperations)
        self.start_time_edit.setGeometry(QtCore.QRect(210, 40, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.start_time_edit.setFont(font)
        self.start_time_edit.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.start_time_edit.setObjectName("start_time_edit")
        self.Heater1Setpoints = QtWidgets.QTableWidget(self.TabOperations)
        self.Heater1Setpoints.setGeometry(QtCore.QRect(20, 260, 211, 231))
        self.Heater1Setpoints.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.Heater1Setpoints.setGridStyle(QtCore.Qt.SolidLine)
        self.Heater1Setpoints.setObjectName("Heater1Setpoints")
        self.Heater1Setpoints.setColumnCount(2)
        self.Heater1Setpoints.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.Heater1Setpoints.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Heater1Setpoints.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Heater1Setpoints.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Heater1Setpoints.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Heater1Setpoints.setItem(0, 1, item)
        self.Heater1Setpoints.horizontalHeader().setVisible(False)
        self.Heater1Setpoints.verticalHeader().setVisible(False)
        self.Heater1Setpoints.verticalHeader().setHighlightSections(True)
        self.Heater1TableAddRowButton = QtWidgets.QPushButton(self.TabOperations)
        self.Heater1TableAddRowButton.setGeometry(QtCore.QRect(60, 500, 131, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Heater1TableAddRowButton.sizePolicy().hasHeightForWidth())
        self.Heater1TableAddRowButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Heater1TableAddRowButton.setFont(font)
        self.Heater1TableAddRowButton.setObjectName("Heater1TableAddRowButton")
        self.label = QtWidgets.QLabel(self.TabOperations)
        self.label.setGeometry(QtCore.QRect(40, 200, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.TabOperations)
        self.label_4.setGeometry(QtCore.QRect(280, 200, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setKerning(True)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.Heater2Setpoints = QtWidgets.QTableWidget(self.TabOperations)
        self.Heater2Setpoints.setGeometry(QtCore.QRect(260, 260, 211, 231))
        self.Heater2Setpoints.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.Heater2Setpoints.setGridStyle(QtCore.Qt.SolidLine)
        self.Heater2Setpoints.setObjectName("Heater2Setpoints")
        self.Heater2Setpoints.setColumnCount(2)
        self.Heater2Setpoints.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.Heater2Setpoints.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Heater2Setpoints.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Heater2Setpoints.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Heater2Setpoints.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Heater2Setpoints.setItem(0, 1, item)
        self.Heater2Setpoints.horizontalHeader().setVisible(False)
        self.Heater2Setpoints.verticalHeader().setVisible(False)
        self.Heater2Setpoints.verticalHeader().setHighlightSections(True)
        self.label_30 = QtWidgets.QLabel(self.TabOperations)
        self.label_30.setGeometry(QtCore.QRect(510, 200, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setKerning(True)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setWordWrap(True)
        self.label_30.setObjectName("label_30")
        self.Heater3Setpoints = QtWidgets.QTableWidget(self.TabOperations)
        self.Heater3Setpoints.setGeometry(QtCore.QRect(490, 260, 211, 231))
        self.Heater3Setpoints.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.Heater3Setpoints.setGridStyle(QtCore.Qt.SolidLine)
        self.Heater3Setpoints.setObjectName("Heater3Setpoints")
        self.Heater3Setpoints.setColumnCount(2)
        self.Heater3Setpoints.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.Heater3Setpoints.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Heater3Setpoints.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Heater3Setpoints.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Heater3Setpoints.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Heater3Setpoints.setItem(0, 1, item)
        self.Heater3Setpoints.horizontalHeader().setVisible(False)
        self.Heater3Setpoints.verticalHeader().setVisible(False)
        self.Heater3Setpoints.verticalHeader().setHighlightSections(True)
        self.Heater2TableAddRowButton = QtWidgets.QPushButton(self.TabOperations)
        self.Heater2TableAddRowButton.setGeometry(QtCore.QRect(300, 500, 131, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Heater2TableAddRowButton.sizePolicy().hasHeightForWidth())
        self.Heater2TableAddRowButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Heater2TableAddRowButton.setFont(font)
        self.Heater2TableAddRowButton.setObjectName("Heater2TableAddRowButton")
        self.Heater3TableAddRowButton = QtWidgets.QPushButton(self.TabOperations)
        self.Heater3TableAddRowButton.setGeometry(QtCore.QRect(530, 500, 131, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Heater3TableAddRowButton.sizePolicy().hasHeightForWidth())
        self.Heater3TableAddRowButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Heater3TableAddRowButton.setFont(font)
        self.Heater3TableAddRowButton.setObjectName("Heater3TableAddRowButton")
        self.Tabs.addTab(self.TabOperations, "")
        self.TabStatus = QtWidgets.QWidget()
        self.TabStatus.setObjectName("TabStatus")
        self.gridLayoutWidget = QtWidgets.QWidget(self.TabStatus)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 19, 671, 411))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.VariableT2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.VariableT2.setObjectName("VariableT2")
        self.gridLayout.addWidget(self.VariableT2, 2, 2, 1, 1)
        self.LabelT2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LabelT2.setObjectName("LabelT2")
        self.gridLayout.addWidget(self.LabelT2, 2, 1, 1, 1)
        self.LabelH1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LabelH1.setObjectName("LabelH1")
        self.gridLayout.addWidget(self.LabelH1, 1, 5, 1, 1)
        self.VariablePress1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.VariablePress1.setObjectName("VariablePress1")
        self.gridLayout.addWidget(self.VariablePress1, 1, 4, 1, 1)
        self.LabelPress4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LabelPress4.setObjectName("LabelPress4")
        self.gridLayout.addWidget(self.LabelPress4, 4, 3, 1, 1)
        self.LabelPump1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LabelPump1.setObjectName("LabelPump1")
        self.gridLayout.addWidget(self.LabelPump1, 5, 5, 1, 1)
        self.VariableT8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.VariableT8.setObjectName("VariableT8")
        self.gridLayout.addWidget(self.VariableT8, 8, 2, 1, 1)
        self.LabelT6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LabelT6.setObjectName("LabelT6")
        self.gridLayout.addWidget(self.LabelT6, 6, 1, 1, 1)
        self.LabelT3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LabelT3.setObjectName("LabelT3")
        self.gridLayout.addWidget(self.LabelT3, 3, 1, 1, 1)
        self.LabelH2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LabelH2.setObjectName("LabelH2")
        self.gridLayout.addWidget(self.LabelH2, 2, 5, 1, 1)
        self.LabelT7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LabelT7.setObjectName("LabelT7")
        self.gridLayout.addWidget(self.LabelT7, 7, 1, 1, 1)
        self.LabelT8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LabelT8.setObjectName("LabelT8")
        self.gridLayout.addWidget(self.LabelT8, 8, 1, 1, 1)
        self.VariableT1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.VariableT1.setObjectName("VariableT1")
        self.gridLayout.addWidget(self.VariableT1, 1, 2, 1, 1)
        self.LabelT1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LabelT1.setAutoFillBackground(True)
        self.LabelT1.setObjectName("LabelT1")
        self.gridLayout.addWidget(self.LabelT1, 1, 1, 1, 1)
        self.HeaderTemperature = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.HeaderTemperature.setFont(font)
        self.HeaderTemperature.setLineWidth(1)
        self.HeaderTemperature.setObjectName("HeaderTemperature")
        self.gridLayout.addWidget(self.HeaderTemperature, 0, 1, 1, 2, QtCore.Qt.AlignHCenter)
        self.LabelPump3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LabelPump3.setObjectName("LabelPump3")
        self.gridLayout.addWidget(self.LabelPump3, 7, 5, 1, 1)
        self.LabelPress3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LabelPress3.setObjectName("LabelPress3")
        self.gridLayout.addWidget(self.LabelPress3, 3, 3, 1, 1)
        self.VariablePress2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.VariablePress2.setObjectName("VariablePress2")
        self.gridLayout.addWidget(self.VariablePress2, 2, 4, 1, 1)
        self.VariableT6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.VariableT6.setObjectName("VariableT6")
        self.gridLayout.addWidget(self.VariableT6, 6, 2, 1, 1)
        self.LabelH3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LabelH3.setObjectName("LabelH3")
        self.gridLayout.addWidget(self.LabelH3, 3, 5, 1, 1)
        self.LabelPress1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LabelPress1.setObjectName("LabelPress1")
        self.gridLayout.addWidget(self.LabelPress1, 1, 3, 1, 1)
        self.VariableT3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.VariableT3.setObjectName("VariableT3")
        self.gridLayout.addWidget(self.VariableT3, 3, 2, 1, 1)
        self.LabelPress2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LabelPress2.setObjectName("LabelPress2")
        self.gridLayout.addWidget(self.LabelPress2, 2, 3, 1, 1)
        self.VariablePress4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.VariablePress4.setObjectName("VariablePress4")
        self.gridLayout.addWidget(self.VariablePress4, 4, 4, 1, 1)
        self.HeaderPressure = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.HeaderPressure.setFont(font)
        self.HeaderPressure.setLineWidth(1)
        self.HeaderPressure.setObjectName("HeaderPressure")
        self.gridLayout.addWidget(self.HeaderPressure, 0, 3, 1, 2, QtCore.Qt.AlignHCenter)
        self.LabelT9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LabelT9.setObjectName("LabelT9")
        self.gridLayout.addWidget(self.LabelT9, 9, 1, 1, 1)
        self.LabelPump2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LabelPump2.setObjectName("LabelPump2")
        self.gridLayout.addWidget(self.LabelPump2, 6, 5, 1, 1)
        self.VariableT7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.VariableT7.setObjectName("VariableT7")
        self.gridLayout.addWidget(self.VariableT7, 7, 2, 1, 1)
        self.VariableT4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.VariableT4.setObjectName("VariableT4")
        self.gridLayout.addWidget(self.VariableT4, 4, 2, 1, 1)
        self.VariableH3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.VariableH3.setObjectName("VariableH3")
        self.gridLayout.addWidget(self.VariableH3, 3, 6, 1, 1)
        self.VariablePump2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.VariablePump2.setObjectName("VariablePump2")
        self.gridLayout.addWidget(self.VariablePump2, 6, 6, 1, 1)
        self.VariableH2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.VariableH2.setObjectName("VariableH2")
        self.gridLayout.addWidget(self.VariableH2, 2, 6, 1, 1)
        self.VariablePress3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.VariablePress3.setObjectName("VariablePress3")
        self.gridLayout.addWidget(self.VariablePress3, 3, 4, 1, 1)
        self.VariableT5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.VariableT5.setObjectName("VariableT5")
        self.gridLayout.addWidget(self.VariableT5, 5, 2, 1, 1)
        self.VariableH1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.VariableH1.setObjectName("VariableH1")
        self.gridLayout.addWidget(self.VariableH1, 1, 6, 1, 1)
        self.LabelT4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LabelT4.setObjectName("LabelT4")
        self.gridLayout.addWidget(self.LabelT4, 4, 1, 1, 1)
        self.VariablePump3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.VariablePump3.setObjectName("VariablePump3")
        self.gridLayout.addWidget(self.VariablePump3, 7, 6, 1, 1)
        self.LabelT5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LabelT5.setObjectName("LabelT5")
        self.gridLayout.addWidget(self.LabelT5, 5, 1, 1, 1)
        self.VariablePump1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.VariablePump1.setObjectName("VariablePump1")
        self.gridLayout.addWidget(self.VariablePump1, 5, 6, 1, 1)
        self.HeaderController = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.HeaderController.setFont(font)
        self.HeaderController.setObjectName("HeaderController")
        self.gridLayout.addWidget(self.HeaderController, 0, 5, 1, 2, QtCore.Qt.AlignHCenter)
        self.VariableT9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.VariableT9.setObjectName("VariableT9")
        self.gridLayout.addWidget(self.VariableT9, 9, 2, 1, 1)
        self.VariableH1SetPoint = QtWidgets.QLabel(self.gridLayoutWidget)
        self.VariableH1SetPoint.setObjectName("VariableH1SetPoint")
        self.gridLayout.addWidget(self.VariableH1SetPoint, 1, 7, 1, 1)
        self.VariableH2SetPoint = QtWidgets.QLabel(self.gridLayoutWidget)
        self.VariableH2SetPoint.setObjectName("VariableH2SetPoint")
        self.gridLayout.addWidget(self.VariableH2SetPoint, 2, 7, 1, 1)
        self.HeaderController_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.HeaderController_2.setFont(font)
        self.HeaderController_2.setObjectName("HeaderController_2")
        self.gridLayout.addWidget(self.HeaderController_2, 0, 7, 1, 1)
        self.VariableH3SetPoint = QtWidgets.QLabel(self.gridLayoutWidget)
        self.VariableH3SetPoint.setObjectName("VariableH3SetPoint")
        self.gridLayout.addWidget(self.VariableH3SetPoint, 3, 7, 1, 1)
        self.Tabs.addTab(self.TabStatus, "")
        self.TabHeater1 = QtWidgets.QWidget()
        self.TabHeater1.setObjectName("TabHeater1")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.TabHeater1)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 20, 711, 241))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.VariableHeater1Temp = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.VariableHeater1Temp.setMaximumSize(QtCore.QSize(500, 40))
        self.VariableHeater1Temp.setObjectName("VariableHeater1Temp")
        self.gridLayout_2.addWidget(self.VariableHeater1Temp, 2, 1, 1, 1)
        self.HeaderDesiredValue_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.HeaderDesiredValue_2.setMaximumSize(QtCore.QSize(500, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.HeaderDesiredValue_2.setFont(font)
        self.HeaderDesiredValue_2.setAlignment(QtCore.Qt.AlignCenter)
        self.HeaderDesiredValue_2.setObjectName("HeaderDesiredValue_2")
        self.gridLayout_2.addWidget(self.HeaderDesiredValue_2, 0, 3, 1, 1)
        self.HeaderDesiredValue = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.HeaderDesiredValue.setMaximumSize(QtCore.QSize(500, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.HeaderDesiredValue.setFont(font)
        self.HeaderDesiredValue.setAlignment(QtCore.Qt.AlignCenter)
        self.HeaderDesiredValue.setObjectName("HeaderDesiredValue")
        self.gridLayout_2.addWidget(self.HeaderDesiredValue, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.LabelHeater1Temp = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.LabelHeater1Temp.setMaximumSize(QtCore.QSize(80, 40))
        self.LabelHeater1Temp.setObjectName("LabelHeater1Temp")
        self.gridLayout_2.addWidget(self.LabelHeater1Temp, 2, 0, 1, 1)
        self.LabelHeater1MaxTemp = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.LabelHeater1MaxTemp.setMaximumSize(QtCore.QSize(500, 40))
        self.LabelHeater1MaxTemp.setObjectName("LabelHeater1MaxTemp")
        self.gridLayout_2.addWidget(self.LabelHeater1MaxTemp, 7, 0, 1, 1)
        self.ButtonUpdateHeater1Setpoints = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.ButtonUpdateHeater1Setpoints.sizePolicy().hasHeightForWidth())
        self.ButtonUpdateHeater1Setpoints.setSizePolicy(sizePolicy)
        self.ButtonUpdateHeater1Setpoints.setMaximumSize(QtCore.QSize(500, 40))
        self.ButtonUpdateHeater1Setpoints.setObjectName("ButtonUpdateHeater1Setpoints")
        self.gridLayout_2.addWidget(self.ButtonUpdateHeater1Setpoints, 4, 3, 3, 1)
        self.InputHeater1MaxTemp = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.InputHeater1MaxTemp.sizePolicy().hasHeightForWidth())
        self.InputHeater1MaxTemp.setSizePolicy(sizePolicy)
        self.InputHeater1MaxTemp.setMaximumSize(QtCore.QSize(80, 30))
        self.InputHeater1MaxTemp.setObjectName("InputHeater1MaxTemp")
        self.gridLayout_2.addWidget(self.InputHeater1MaxTemp, 7, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.CBHeater1TSensor = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.CBHeater1TSensor.setObjectName("CBHeater1TSensor")
        self.gridLayout_2.addWidget(self.CBHeater1TSensor, 1, 2, 1, 1)
        self.LabelHeater1TSensor = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.LabelHeater1TSensor.setObjectName("LabelHeater1TSensor")
        self.gridLayout_2.addWidget(self.LabelHeater1TSensor, 1, 0, 1, 2)
        self.VariableHeater1MaxTemp = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.VariableHeater1MaxTemp.setMaximumSize(QtCore.QSize(500, 40))
        self.VariableHeater1MaxTemp.setObjectName("VariableHeater1MaxTemp")
        self.gridLayout_2.addWidget(self.VariableHeater1MaxTemp, 7, 1, 1, 1)
        self.LabelHeaterStatus = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.LabelHeaterStatus.setMaximumSize(QtCore.QSize(500, 40))
        self.LabelHeaterStatus.setObjectName("LabelHeaterStatus")
        self.gridLayout_2.addWidget(self.LabelHeaterStatus, 3, 0, 1, 1)
        self.VariableHeater1Status = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.VariableHeater1Status.setMaximumSize(QtCore.QSize(500, 40))
        self.VariableHeater1Status.setObjectName("VariableHeater1Status")
        self.gridLayout_2.addWidget(self.VariableHeater1Status, 3, 1, 1, 1)
        self.ButtonUpdateHeater1MaxTemp = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.ButtonUpdateHeater1MaxTemp.setMaximumSize(QtCore.QSize(500, 40))
        self.ButtonUpdateHeater1MaxTemp.setObjectName("ButtonUpdateHeater1MaxTemp")
        self.gridLayout_2.addWidget(self.ButtonUpdateHeater1MaxTemp, 7, 3, 1, 1)
        self.VariableHeater1Upper = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.VariableHeater1Upper.setMaximumSize(QtCore.QSize(500, 40))
        self.VariableHeater1Upper.setObjectName("VariableHeater1Upper")
        self.gridLayout_2.addWidget(self.VariableHeater1Upper, 4, 1, 1, 1)
        self.InputHeater1Upper = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.InputHeater1Upper.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputHeater1Upper.sizePolicy().hasHeightForWidth())
        self.InputHeater1Upper.setSizePolicy(sizePolicy)
        self.InputHeater1Upper.setMaximumSize(QtCore.QSize(80, 30))
        self.InputHeater1Upper.setObjectName("InputHeater1Upper")
        self.gridLayout_2.addWidget(self.InputHeater1Upper, 4, 2, 1, 1)
        self.LabelHeater1Upper = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.LabelHeater1Upper.setObjectName("LabelHeater1Upper")
        self.gridLayout_2.addWidget(self.LabelHeater1Upper, 4, 0, 1, 1)
        self.VariableHeater1Lower = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.VariableHeater1Lower.setMaximumSize(QtCore.QSize(500, 40))
        self.VariableHeater1Lower.setObjectName("VariableHeater1Lower")
        self.gridLayout_2.addWidget(self.VariableHeater1Lower, 5, 1, 2, 1)
        self.LabelHeater1Lower = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.LabelHeater1Lower.setMaximumSize(QtCore.QSize(500, 40))
        self.LabelHeater1Lower.setObjectName("LabelHeater1Lower")
        self.gridLayout_2.addWidget(self.LabelHeater1Lower, 5, 0, 2, 1)
        self.InputHeater1Lower = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputHeater1Lower.sizePolicy().hasHeightForWidth())
        self.InputHeater1Lower.setSizePolicy(sizePolicy)
        self.InputHeater1Lower.setMaximumSize(QtCore.QSize(80, 30))
        self.InputHeater1Lower.setObjectName("InputHeater1Lower")
        self.gridLayout_2.addWidget(self.InputHeater1Lower, 5, 2, 2, 1)
        self.Tabs.addTab(self.TabHeater1, "")
        self.TabHeater2 = QtWidgets.QWidget()
        self.TabHeater2.setObjectName("TabHeater2")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.TabHeater2)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 20, 711, 241))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.InputHeater2Lower = QtWidgets.QTextEdit(self.gridLayoutWidget_3)
        self.InputHeater2Lower.setMaximumSize(QtCore.QSize(80, 30))
        self.InputHeater2Lower.setObjectName("InputHeater2Lower")
        self.gridLayout_3.addWidget(self.InputHeater2Lower, 6, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.ButtonUpdateHeater2Setpoints = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.ButtonUpdateHeater2Setpoints.setMaximumSize(QtCore.QSize(500, 40))
        self.ButtonUpdateHeater2Setpoints.setObjectName("ButtonUpdateHeater2Setpoints")
        self.gridLayout_3.addWidget(self.ButtonUpdateHeater2Setpoints, 4, 3, 3, 1)
        self.InputHeater2MaxTemp = QtWidgets.QTextEdit(self.gridLayoutWidget_3)
        self.InputHeater2MaxTemp.setMaximumSize(QtCore.QSize(80, 30))
        self.InputHeater2MaxTemp.setObjectName("InputHeater2MaxTemp")
        self.gridLayout_3.addWidget(self.InputHeater2MaxTemp, 7, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.VariableHeater2Status = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.VariableHeater2Status.setMaximumSize(QtCore.QSize(500, 40))
        self.VariableHeater2Status.setObjectName("VariableHeater2Status")
        self.gridLayout_3.addWidget(self.VariableHeater2Status, 3, 1, 1, 1)
        self.LabelHeater2Status = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.LabelHeater2Status.setMaximumSize(QtCore.QSize(151, 16))
        self.LabelHeater2Status.setObjectName("LabelHeater2Status")
        self.gridLayout_3.addWidget(self.LabelHeater2Status, 3, 0, 1, 1)
        self.ButtonUpdateHeater2MaxTemp = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.ButtonUpdateHeater2MaxTemp.setMaximumSize(QtCore.QSize(500, 40))
        self.ButtonUpdateHeater2MaxTemp.setObjectName("ButtonUpdateHeater2MaxTemp")
        self.gridLayout_3.addWidget(self.ButtonUpdateHeater2MaxTemp, 7, 3, 1, 1)
        self.HeaderDesiredValue_3 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.HeaderDesiredValue_3.setMaximumSize(QtCore.QSize(500, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.HeaderDesiredValue_3.setFont(font)
        self.HeaderDesiredValue_3.setAlignment(QtCore.Qt.AlignCenter)
        self.HeaderDesiredValue_3.setObjectName("HeaderDesiredValue_3")
        self.gridLayout_3.addWidget(self.HeaderDesiredValue_3, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.LabelHeater2MaxTemp = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelHeater2MaxTemp.sizePolicy().hasHeightForWidth())
        self.LabelHeater2MaxTemp.setSizePolicy(sizePolicy)
        self.LabelHeater2MaxTemp.setMaximumSize(QtCore.QSize(151, 71))
        self.LabelHeater2MaxTemp.setObjectName("LabelHeater2MaxTemp")
        self.gridLayout_3.addWidget(self.LabelHeater2MaxTemp, 7, 0, 1, 1)
        self.VariableHeater2Temp = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.VariableHeater2Temp.setMaximumSize(QtCore.QSize(500, 40))
        self.VariableHeater2Temp.setObjectName("VariableHeater2Temp")
        self.gridLayout_3.addWidget(self.VariableHeater2Temp, 2, 1, 1, 1)
        self.LabelHeater2Temp = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.LabelHeater2Temp.setMaximumSize(QtCore.QSize(151, 16))
        self.LabelHeater2Temp.setObjectName("LabelHeater2Temp")
        self.gridLayout_3.addWidget(self.LabelHeater2Temp, 2, 0, 1, 1)
        self.VariableHeater2MaxTemp = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.VariableHeater2MaxTemp.setMaximumSize(QtCore.QSize(500, 40))
        self.VariableHeater2MaxTemp.setObjectName("VariableHeater2MaxTemp")
        self.gridLayout_3.addWidget(self.VariableHeater2MaxTemp, 7, 1, 1, 1)
        self.HeaderDesiredValue_4 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.HeaderDesiredValue_4.setMaximumSize(QtCore.QSize(500, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.HeaderDesiredValue_4.setFont(font)
        self.HeaderDesiredValue_4.setAlignment(QtCore.Qt.AlignCenter)
        self.HeaderDesiredValue_4.setObjectName("HeaderDesiredValue_4")
        self.gridLayout_3.addWidget(self.HeaderDesiredValue_4, 0, 3, 1, 1)
        self.VariableHeater2Lower = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.VariableHeater2Lower.setMaximumSize(QtCore.QSize(500, 40))
        self.VariableHeater2Lower.setObjectName("VariableHeater2Lower")
        self.gridLayout_3.addWidget(self.VariableHeater2Lower, 6, 1, 1, 1)
        self.LabelHeater2LowerName = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.LabelHeater2LowerName.setMaximumSize(QtCore.QSize(500, 40))
        self.LabelHeater2LowerName.setObjectName("LabelHeater2LowerName")
        self.gridLayout_3.addWidget(self.LabelHeater2LowerName, 6, 0, 1, 1)
        self.LabelHeater2TSensor = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.LabelHeater2TSensor.setObjectName("LabelHeater2TSensor")
        self.gridLayout_3.addWidget(self.LabelHeater2TSensor, 1, 0, 1, 2)
        self.CBHeater2TSensor = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.CBHeater2TSensor.setObjectName("CBHeater2TSensor")
        self.gridLayout_3.addWidget(self.CBHeater2TSensor, 1, 2, 1, 1)
        self.LabelHeater2UpperName = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelHeater2UpperName.sizePolicy().hasHeightForWidth())
        self.LabelHeater2UpperName.setSizePolicy(sizePolicy)
        self.LabelHeater2UpperName.setMaximumSize(QtCore.QSize(500, 40))
        self.LabelHeater2UpperName.setObjectName("LabelHeater2UpperName")
        self.gridLayout_3.addWidget(self.LabelHeater2UpperName, 4, 0, 2, 1)
        self.VariableHeater2Upper = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.VariableHeater2Upper.setMaximumSize(QtCore.QSize(500, 40))
        self.VariableHeater2Upper.setObjectName("VariableHeater2Upper")
        self.gridLayout_3.addWidget(self.VariableHeater2Upper, 4, 1, 2, 1)
        self.InputHeater2Upper = QtWidgets.QTextEdit(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputHeater2Upper.sizePolicy().hasHeightForWidth())
        self.InputHeater2Upper.setSizePolicy(sizePolicy)
        self.InputHeater2Upper.setMaximumSize(QtCore.QSize(80, 30))
        self.InputHeater2Upper.setObjectName("InputHeater2Upper")
        self.gridLayout_3.addWidget(self.InputHeater2Upper, 4, 2, 2, 1)
        self.Tabs.addTab(self.TabHeater2, "")
        self.TabHeater3 = QtWidgets.QWidget()
        self.TabHeater3.setObjectName("TabHeater3")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.TabHeater3)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(0, 23, 711, 241))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.VariableHeater3MaxTemp = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.VariableHeater3MaxTemp.setMaximumSize(QtCore.QSize(500, 80))
        self.VariableHeater3MaxTemp.setObjectName("VariableHeater3MaxTemp")
        self.gridLayout_4.addWidget(self.VariableHeater3MaxTemp, 7, 1, 1, 1)
        self.LabelHeater3Temp = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.LabelHeater3Temp.setMaximumSize(QtCore.QSize(500, 80))
        self.LabelHeater3Temp.setObjectName("LabelHeater3Temp")
        self.gridLayout_4.addWidget(self.LabelHeater3Temp, 2, 0, 1, 1)
        self.LabelHeater3Lower = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.LabelHeater3Lower.setMaximumSize(QtCore.QSize(500, 40))
        self.LabelHeater3Lower.setObjectName("LabelHeater3Lower")
        self.gridLayout_4.addWidget(self.LabelHeater3Lower, 6, 0, 1, 1)
        self.VariableHeater3Status = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.VariableHeater3Status.setMaximumSize(QtCore.QSize(500, 80))
        self.VariableHeater3Status.setObjectName("VariableHeater3Status")
        self.gridLayout_4.addWidget(self.VariableHeater3Status, 3, 1, 1, 1)
        self.HeaderDesiredValue_6 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.HeaderDesiredValue_6.setFont(font)
        self.HeaderDesiredValue_6.setAlignment(QtCore.Qt.AlignCenter)
        self.HeaderDesiredValue_6.setObjectName("HeaderDesiredValue_6")
        self.gridLayout_4.addWidget(self.HeaderDesiredValue_6, 0, 3, 1, 1)
        self.InputHeater3MaxTemp = QtWidgets.QTextEdit(self.gridLayoutWidget_4)
        self.InputHeater3MaxTemp.setMaximumSize(QtCore.QSize(80, 30))
        self.InputHeater3MaxTemp.setObjectName("InputHeater3MaxTemp")
        self.gridLayout_4.addWidget(self.InputHeater3MaxTemp, 7, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.LabelHeater3MaxTemp = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.LabelHeater3MaxTemp.setMaximumSize(QtCore.QSize(500, 80))
        self.LabelHeater3MaxTemp.setObjectName("LabelHeater3MaxTemp")
        self.gridLayout_4.addWidget(self.LabelHeater3MaxTemp, 7, 0, 1, 1)
        self.VariableHeater3Temp = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.VariableHeater3Temp.setMaximumSize(QtCore.QSize(500, 80))
        self.VariableHeater3Temp.setObjectName("VariableHeater3Temp")
        self.gridLayout_4.addWidget(self.VariableHeater3Temp, 2, 1, 1, 1)
        self.VariableHeater3Lower = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.VariableHeater3Lower.setMaximumSize(QtCore.QSize(500, 40))
        self.VariableHeater3Lower.setObjectName("VariableHeater3Lower")
        self.gridLayout_4.addWidget(self.VariableHeater3Lower, 6, 1, 1, 1)
        self.ButtonUpdateHeater3MaxTemp = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.ButtonUpdateHeater3MaxTemp.setMaximumSize(QtCore.QSize(500, 40))
        self.ButtonUpdateHeater3MaxTemp.setObjectName("ButtonUpdateHeater3MaxTemp")
        self.gridLayout_4.addWidget(self.ButtonUpdateHeater3MaxTemp, 7, 3, 1, 1)
        self.LabelHeater3Status = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.LabelHeater3Status.setMaximumSize(QtCore.QSize(500, 80))
        self.LabelHeater3Status.setObjectName("LabelHeater3Status")
        self.gridLayout_4.addWidget(self.LabelHeater3Status, 3, 0, 1, 1)
        self.HeaderDesiredValue_5 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.HeaderDesiredValue_5.setFont(font)
        self.HeaderDesiredValue_5.setAlignment(QtCore.Qt.AlignCenter)
        self.HeaderDesiredValue_5.setObjectName("HeaderDesiredValue_5")
        self.gridLayout_4.addWidget(self.HeaderDesiredValue_5, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.InputHeater3Lower = QtWidgets.QTextEdit(self.gridLayoutWidget_4)
        self.InputHeater3Lower.setMaximumSize(QtCore.QSize(80, 30))
        self.InputHeater3Lower.setObjectName("InputHeater3Lower")
        self.gridLayout_4.addWidget(self.InputHeater3Lower, 6, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.ButtonUpdateHeater3Setpoints = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.ButtonUpdateHeater3Setpoints.sizePolicy().hasHeightForWidth())
        self.ButtonUpdateHeater3Setpoints.setSizePolicy(sizePolicy)
        self.ButtonUpdateHeater3Setpoints.setMaximumSize(QtCore.QSize(500, 40))
        self.ButtonUpdateHeater3Setpoints.setObjectName("ButtonUpdateHeater3Setpoints")
        self.gridLayout_4.addWidget(self.ButtonUpdateHeater3Setpoints, 4, 3, 3, 1)
        self.LabelHeater3TSensor = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.LabelHeater3TSensor.setObjectName("LabelHeater3TSensor")
        self.gridLayout_4.addWidget(self.LabelHeater3TSensor, 1, 0, 1, 2)
        self.CBHeater3TSensor = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.CBHeater3TSensor.setObjectName("CBHeater3TSensor")
        self.gridLayout_4.addWidget(self.CBHeater3TSensor, 1, 2, 1, 1)
        self.LabelHeater3Upper = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.LabelHeater3Upper.setMaximumSize(QtCore.QSize(500, 40))
        self.LabelHeater3Upper.setObjectName("LabelHeater3Upper")
        self.gridLayout_4.addWidget(self.LabelHeater3Upper, 4, 0, 2, 1)
        self.VariableHeater3Upper = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.VariableHeater3Upper.setMaximumSize(QtCore.QSize(500, 40))
        self.VariableHeater3Upper.setObjectName("VariableHeater3Upper")
        self.gridLayout_4.addWidget(self.VariableHeater3Upper, 4, 1, 2, 1)
        self.InputHeater3Upper = QtWidgets.QTextEdit(self.gridLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputHeater3Upper.sizePolicy().hasHeightForWidth())
        self.InputHeater3Upper.setSizePolicy(sizePolicy)
        self.InputHeater3Upper.setMaximumSize(QtCore.QSize(80, 30))
        self.InputHeater3Upper.setObjectName("InputHeater3Upper")
        self.gridLayout_4.addWidget(self.InputHeater3Upper, 4, 2, 2, 1)
        self.Tabs.addTab(self.TabHeater3, "")
        self.TabPump1 = QtWidgets.QWidget()
        self.TabPump1.setEnabled(True)
        self.TabPump1.setAccessibleName("")
        self.TabPump1.setObjectName("TabPump1")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.TabPump1)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(10, 20, 691, 231))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.VariablePump1Upper = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.VariablePump1Upper.setObjectName("VariablePump1Upper")
        self.gridLayout_5.addWidget(self.VariablePump1Upper, 5, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 9, 0, 1, 1)
        self.InputPump1VolUpper = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputPump1VolUpper.sizePolicy().hasHeightForWidth())
        self.InputPump1VolUpper.setSizePolicy(sizePolicy)
        self.InputPump1VolUpper.setInputMethodHints(QtCore.Qt.ImhNone)
        self.InputPump1VolUpper.setObjectName("InputPump1VolUpper")
        self.gridLayout_5.addWidget(self.InputPump1VolUpper, 5, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 0, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 8, 0, 1, 1)
        self.InputPump1VolIntercept = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputPump1VolIntercept.sizePolicy().hasHeightForWidth())
        self.InputPump1VolIntercept.setSizePolicy(sizePolicy)
        self.InputPump1VolIntercept.setAlignment(QtCore.Qt.AlignCenter)
        self.InputPump1VolIntercept.setObjectName("InputPump1VolIntercept")
        self.gridLayout_5.addWidget(self.InputPump1VolIntercept, 9, 2, 1, 1)
        self.VariablePump1Volume = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.VariablePump1Volume.setObjectName("VariablePump1Volume")
        self.gridLayout_5.addWidget(self.VariablePump1Volume, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 0, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 3, 0, 1, 1)
        self.InputPump1VolSlope = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputPump1VolSlope.sizePolicy().hasHeightForWidth())
        self.InputPump1VolSlope.setSizePolicy(sizePolicy)
        self.InputPump1VolSlope.setAlignment(QtCore.Qt.AlignCenter)
        self.InputPump1VolSlope.setObjectName("InputPump1VolSlope")
        self.gridLayout_5.addWidget(self.InputPump1VolSlope, 8, 2, 1, 1)
        self.VariablePump1VolSlope = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.VariablePump1VolSlope.setObjectName("VariablePump1VolSlope")
        self.gridLayout_5.addWidget(self.VariablePump1VolSlope, 8, 1, 1, 1)
        self.VariablePump1Pressure = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.VariablePump1Pressure.setObjectName("VariablePump1Pressure")
        self.gridLayout_5.addWidget(self.VariablePump1Pressure, 7, 1, 1, 1)
        self.CBPump1PSensor = QtWidgets.QComboBox(self.gridLayoutWidget_5)
        self.CBPump1PSensor.setObjectName("CBPump1PSensor")
        self.gridLayout_5.addWidget(self.CBPump1PSensor, 1, 2, 1, 1)
        self.InputPump1VolLower = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputPump1VolLower.sizePolicy().hasHeightForWidth())
        self.InputPump1VolLower.setSizePolicy(sizePolicy)
        self.InputPump1VolLower.setObjectName("InputPump1VolLower")
        self.gridLayout_5.addWidget(self.InputPump1VolLower, 6, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 7, 0, 1, 1)
        self.LabelPump1UpperLimit = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.LabelPump1UpperLimit.setObjectName("LabelPump1UpperLimit")
        self.gridLayout_5.addWidget(self.LabelPump1UpperLimit, 5, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 0, 1, 1, 1)
        self.ButtonUpdatePump1VolCalcInputs = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.ButtonUpdatePump1VolCalcInputs.setInputMethodHints(QtCore.Qt.ImhNone)
        self.ButtonUpdatePump1VolCalcInputs.setObjectName("ButtonUpdatePump1VolCalcInputs")
        self.gridLayout_5.addWidget(self.ButtonUpdatePump1VolCalcInputs, 8, 3, 2, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 0, 0, 1, 1)
        self.LabelPump1LowerLimit = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.LabelPump1LowerLimit.setObjectName("LabelPump1LowerLimit")
        self.gridLayout_5.addWidget(self.LabelPump1LowerLimit, 6, 0, 1, 1)
        self.LabelPump1PSensor = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.LabelPump1PSensor.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LabelPump1PSensor.setObjectName("LabelPump1PSensor")
        self.gridLayout_5.addWidget(self.LabelPump1PSensor, 1, 0, 1, 2)
        self.VariablePump1Lower = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.VariablePump1Lower.setObjectName("VariablePump1Lower")
        self.gridLayout_5.addWidget(self.VariablePump1Lower, 6, 1, 1, 1)
        self.VariablePump1VolIntercept = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.VariablePump1VolIntercept.setObjectName("VariablePump1VolIntercept")
        self.gridLayout_5.addWidget(self.VariablePump1VolIntercept, 9, 1, 1, 1)
        self.ButtonUpdatePump1Setpoints = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.ButtonUpdatePump1Setpoints.setObjectName("ButtonUpdatePump1Setpoints")
        self.gridLayout_5.addWidget(self.ButtonUpdatePump1Setpoints, 5, 3, 2, 1)
        self.label_31 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_31.setObjectName("label_31")
        self.gridLayout_5.addWidget(self.label_31, 2, 0, 1, 1)
        self.LabelPump1Status = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.LabelPump1Status.setObjectName("LabelPump1Status")
        self.gridLayout_5.addWidget(self.LabelPump1Status, 2, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.TabPump1)
        self.label_15.setGeometry(QtCore.QRect(220, 260, 291, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.Tabs.addTab(self.TabPump1, "")
        self.TabPump2 = QtWidgets.QWidget()
        self.TabPump2.setObjectName("TabPump2")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.TabPump2)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(10, 20, 691, 231))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_6.addWidget(self.label_14, 0, 3, 1, 1)
        self.VariablePump2VolSlope = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.VariablePump2VolSlope.setObjectName("VariablePump2VolSlope")
        self.gridLayout_6.addWidget(self.VariablePump2VolSlope, 7, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_12.setObjectName("label_12")
        self.gridLayout_6.addWidget(self.label_12, 7, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 8, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_16.setObjectName("label_16")
        self.gridLayout_6.addWidget(self.label_16, 3, 0, 1, 1)
        self.InputPump2VolSlope = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputPump2VolSlope.sizePolicy().hasHeightForWidth())
        self.InputPump2VolSlope.setSizePolicy(sizePolicy)
        self.InputPump2VolSlope.setAlignment(QtCore.Qt.AlignCenter)
        self.InputPump2VolSlope.setObjectName("InputPump2VolSlope")
        self.gridLayout_6.addWidget(self.InputPump2VolSlope, 7, 2, 1, 1)
        self.VariablePump2Pressure = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.VariablePump2Pressure.setObjectName("VariablePump2Pressure")
        self.gridLayout_6.addWidget(self.VariablePump2Pressure, 6, 1, 1, 1)
        self.CBPump2PSensor = QtWidgets.QComboBox(self.gridLayoutWidget_6)
        self.CBPump2PSensor.setObjectName("CBPump2PSensor")
        self.gridLayout_6.addWidget(self.CBPump2PSensor, 1, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_17.setObjectName("label_17")
        self.gridLayout_6.addWidget(self.label_17, 6, 0, 1, 1)
        self.InputPump2VolIntercept = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputPump2VolIntercept.sizePolicy().hasHeightForWidth())
        self.InputPump2VolIntercept.setSizePolicy(sizePolicy)
        self.InputPump2VolIntercept.setAlignment(QtCore.Qt.AlignCenter)
        self.InputPump2VolIntercept.setObjectName("InputPump2VolIntercept")
        self.gridLayout_6.addWidget(self.InputPump2VolIntercept, 8, 2, 1, 1)
        self.VariablePump2Volume = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.VariablePump2Volume.setObjectName("VariablePump2Volume")
        self.gridLayout_6.addWidget(self.VariablePump2Volume, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 0, 2, 1, 1)
        self.VariablePump2VolIntercept = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.VariablePump2VolIntercept.setObjectName("VariablePump2VolIntercept")
        self.gridLayout_6.addWidget(self.VariablePump2VolIntercept, 8, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_6.addWidget(self.label_18, 0, 1, 1, 1)
        self.LabelPump2UpperLimit = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.LabelPump2UpperLimit.setObjectName("LabelPump2UpperLimit")
        self.gridLayout_6.addWidget(self.LabelPump2UpperLimit, 4, 0, 1, 1)
        self.InputPump2VolUpper = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputPump2VolUpper.sizePolicy().hasHeightForWidth())
        self.InputPump2VolUpper.setSizePolicy(sizePolicy)
        self.InputPump2VolUpper.setInputMethodHints(QtCore.Qt.ImhNone)
        self.InputPump2VolUpper.setObjectName("InputPump2VolUpper")
        self.gridLayout_6.addWidget(self.InputPump2VolUpper, 4, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_6.addWidget(self.label_19, 0, 0, 1, 1)
        self.LabelPump2LowerLimit = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.LabelPump2LowerLimit.setObjectName("LabelPump2LowerLimit")
        self.gridLayout_6.addWidget(self.LabelPump2LowerLimit, 5, 0, 1, 1)
        self.ButtonUpdatePump2VolCalcInputs = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.ButtonUpdatePump2VolCalcInputs.setInputMethodHints(QtCore.Qt.ImhNone)
        self.ButtonUpdatePump2VolCalcInputs.setObjectName("ButtonUpdatePump2VolCalcInputs")
        self.gridLayout_6.addWidget(self.ButtonUpdatePump2VolCalcInputs, 7, 3, 2, 1)
        self.ButtonUpdatePump2Setpoints = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.ButtonUpdatePump2Setpoints.setObjectName("ButtonUpdatePump2Setpoints")
        self.gridLayout_6.addWidget(self.ButtonUpdatePump2Setpoints, 4, 3, 2, 1)
        self.LabelPump2PSensor = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.LabelPump2PSensor.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LabelPump2PSensor.setObjectName("LabelPump2PSensor")
        self.gridLayout_6.addWidget(self.LabelPump2PSensor, 1, 0, 1, 2)
        self.VariablePump2Upper = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.VariablePump2Upper.setObjectName("VariablePump2Upper")
        self.gridLayout_6.addWidget(self.VariablePump2Upper, 4, 1, 1, 1)
        self.InputPump2VolLower = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputPump2VolLower.sizePolicy().hasHeightForWidth())
        self.InputPump2VolLower.setSizePolicy(sizePolicy)
        self.InputPump2VolLower.setObjectName("InputPump2VolLower")
        self.gridLayout_6.addWidget(self.InputPump2VolLower, 5, 2, 1, 1)
        self.VariablePump2Lower = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.VariablePump2Lower.setObjectName("VariablePump2Lower")
        self.gridLayout_6.addWidget(self.VariablePump2Lower, 5, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_32.setObjectName("label_32")
        self.gridLayout_6.addWidget(self.label_32, 2, 0, 1, 1)
        self.LabelPump2Status = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.LabelPump2Status.setObjectName("LabelPump2Status")
        self.gridLayout_6.addWidget(self.LabelPump2Status, 2, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.TabPump2)
        self.label_21.setGeometry(QtCore.QRect(220, 260, 291, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.Tabs.addTab(self.TabPump2, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(10, 20, 691, 231))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_7.addWidget(self.label_22, 0, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_20.setObjectName("label_20")
        self.gridLayout_7.addWidget(self.label_20, 8, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_23.setObjectName("label_23")
        self.gridLayout_7.addWidget(self.label_23, 7, 0, 1, 1)
        self.VariablePump3VolSlope = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.VariablePump3VolSlope.setObjectName("VariablePump3VolSlope")
        self.gridLayout_7.addWidget(self.VariablePump3VolSlope, 7, 1, 1, 1)
        self.LabelPump2UpperLimit_2 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.LabelPump2UpperLimit_2.setObjectName("LabelPump2UpperLimit_2")
        self.gridLayout_7.addWidget(self.LabelPump2UpperLimit_2, 4, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_7.addWidget(self.label_27, 0, 1, 1, 1)
        self.LabelPump3PSensor = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.LabelPump3PSensor.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LabelPump3PSensor.setObjectName("LabelPump3PSensor")
        self.gridLayout_7.addWidget(self.LabelPump3PSensor, 1, 0, 1, 2)
        self.VariablePump3VolIntercept = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.VariablePump3VolIntercept.setObjectName("VariablePump3VolIntercept")
        self.gridLayout_7.addWidget(self.VariablePump3VolIntercept, 8, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_25.setObjectName("label_25")
        self.gridLayout_7.addWidget(self.label_25, 3, 0, 1, 1)
        self.VariablePump3Upper = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.VariablePump3Upper.setObjectName("VariablePump3Upper")
        self.gridLayout_7.addWidget(self.VariablePump3Upper, 4, 1, 1, 1)
        self.VariablePump3Lower = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.VariablePump3Lower.setObjectName("VariablePump3Lower")
        self.gridLayout_7.addWidget(self.VariablePump3Lower, 5, 1, 1, 1)
        self.InputPump3VolLower = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputPump3VolLower.sizePolicy().hasHeightForWidth())
        self.InputPump3VolLower.setSizePolicy(sizePolicy)
        self.InputPump3VolLower.setObjectName("InputPump3VolLower")
        self.gridLayout_7.addWidget(self.InputPump3VolLower, 5, 2, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout_7.addWidget(self.label_28, 0, 0, 1, 1)
        self.ButtonUpdatePump3VolCalcInputs = QtWidgets.QPushButton(self.gridLayoutWidget_7)
        self.ButtonUpdatePump3VolCalcInputs.setInputMethodHints(QtCore.Qt.ImhNone)
        self.ButtonUpdatePump3VolCalcInputs.setObjectName("ButtonUpdatePump3VolCalcInputs")
        self.gridLayout_7.addWidget(self.ButtonUpdatePump3VolCalcInputs, 7, 3, 2, 1)
        self.InputPump3VolSlope = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputPump3VolSlope.sizePolicy().hasHeightForWidth())
        self.InputPump3VolSlope.setSizePolicy(sizePolicy)
        self.InputPump3VolSlope.setAlignment(QtCore.Qt.AlignCenter)
        self.InputPump3VolSlope.setObjectName("InputPump3VolSlope")
        self.gridLayout_7.addWidget(self.InputPump3VolSlope, 7, 2, 1, 1)
        self.LabelPump2LowerLimit_2 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.LabelPump2LowerLimit_2.setObjectName("LabelPump2LowerLimit_2")
        self.gridLayout_7.addWidget(self.LabelPump2LowerLimit_2, 5, 0, 1, 1)
        self.InputPump3VolUpper = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputPump3VolUpper.sizePolicy().hasHeightForWidth())
        self.InputPump3VolUpper.setSizePolicy(sizePolicy)
        self.InputPump3VolUpper.setInputMethodHints(QtCore.Qt.ImhNone)
        self.InputPump3VolUpper.setObjectName("InputPump3VolUpper")
        self.gridLayout_7.addWidget(self.InputPump3VolUpper, 4, 2, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_7.addWidget(self.label_24, 0, 3, 1, 1)
        self.InputPump3VolIntercept = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputPump3VolIntercept.sizePolicy().hasHeightForWidth())
        self.InputPump3VolIntercept.setSizePolicy(sizePolicy)
        self.InputPump3VolIntercept.setAlignment(QtCore.Qt.AlignCenter)
        self.InputPump3VolIntercept.setObjectName("InputPump3VolIntercept")
        self.gridLayout_7.addWidget(self.InputPump3VolIntercept, 8, 2, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_26.setObjectName("label_26")
        self.gridLayout_7.addWidget(self.label_26, 6, 0, 1, 1)
        self.ButtonUpdatePump3Setpoints = QtWidgets.QPushButton(self.gridLayoutWidget_7)
        self.ButtonUpdatePump3Setpoints.setObjectName("ButtonUpdatePump3Setpoints")
        self.gridLayout_7.addWidget(self.ButtonUpdatePump3Setpoints, 4, 3, 2, 1)
        self.VariablePump3Pressure = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.VariablePump3Pressure.setObjectName("VariablePump3Pressure")
        self.gridLayout_7.addWidget(self.VariablePump3Pressure, 6, 1, 1, 1)
        self.VariablePump3Volume = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.VariablePump3Volume.setObjectName("VariablePump3Volume")
        self.gridLayout_7.addWidget(self.VariablePump3Volume, 3, 1, 1, 1)
        self.CBPump3PSensor = QtWidgets.QComboBox(self.gridLayoutWidget_7)
        self.CBPump3PSensor.setObjectName("CBPump3PSensor")
        self.gridLayout_7.addWidget(self.CBPump3PSensor, 1, 2, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_33.setObjectName("label_33")
        self.gridLayout_7.addWidget(self.label_33, 2, 0, 1, 1)
        self.LabelPump3Status = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.LabelPump3Status.setObjectName("LabelPump3Status")
        self.gridLayout_7.addWidget(self.LabelPump3Status, 2, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.tab_2)
        self.label_29.setGeometry(QtCore.QRect(220, 260, 291, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.Tabs.addTab(self.tab_2, "")
        self.serialLabel = QtWidgets.QLabel(self.centralwidget)
        self.serialLabel.setGeometry(QtCore.QRect(20, 20, 202, 23))
        self.serialLabel.setObjectName("serialLabel")
        self.Button_startSerial = QtWidgets.QPushButton(self.centralwidget)
        self.Button_startSerial.setGeometry(QtCore.QRect(240, 20, 409, 23))
        self.Button_startSerial.setObjectName("Button_startSerial")
        self.Clock = QtWidgets.QWidget(self.centralwidget)
        self.Clock.setGeometry(QtCore.QRect(840, 10, 161, 61))
        self.Clock.setObjectName("Clock")
        self.CurrentTimeLabel = QtWidgets.QLabel(self.centralwidget)
        self.CurrentTimeLabel.setGeometry(QtCore.QRect(660, 30, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.CurrentTimeLabel.setFont(font)
        self.CurrentTimeLabel.setObjectName("CurrentTimeLabel")
        self.CurrentTimeLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.CurrentTimeLabel_2.setGeometry(QtCore.QRect(660, 80, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.CurrentTimeLabel_2.setFont(font)
        self.CurrentTimeLabel_2.setObjectName("CurrentTimeLabel_2")
        self.BrewingTimeWidget = QtWidgets.QWidget(self.centralwidget)
        self.BrewingTimeWidget.setGeometry(QtCore.QRect(840, 60, 161, 61))
        self.BrewingTimeWidget.setObjectName("BrewingTimeWidget")
        self.PausePushButton = QtWidgets.QPushButton(self.centralwidget)
        self.PausePushButton.setGeometry(QtCore.QRect(750, 130, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.PausePushButton.setFont(font)
        self.PausePushButton.setObjectName("PausePushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1030, 21))
        self.menubar.setObjectName("menubar")
        self.menuWelcome_to_the_CCBC_Brewery = QtWidgets.QMenu(self.menubar)
        self.menuWelcome_to_the_CCBC_Brewery.setObjectName("menuWelcome_to_the_CCBC_Brewery")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuWelcome_to_the_CCBC_Brewery.menuAction())

        self.retranslateUi(MainWindow)
        self.Tabs.setCurrentIndex(6)
        self.Button_startSerial.clicked.connect(MainWindow.update)
        self.ButtonUpdateHeater1Setpoints.clicked.connect(MainWindow.update)
        self.ButtonUpdateHeater1MaxTemp.clicked.connect(MainWindow.update)
        self.ButtonUpdateHeater2Setpoints.clicked.connect(MainWindow.update)
        self.ButtonUpdateHeater2MaxTemp.clicked.connect(MainWindow.update)
        self.ButtonUpdateHeater3MaxTemp.clicked.connect(MainWindow.update)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.StartTimeLabel.setText(_translate("MainWindow", "Start Time:"))
        self.StartNowButton.setText(_translate("MainWindow", "Start Now"))
        self.pushButton_2.setText(_translate("MainWindow", "Start with Delay"))
        item = self.Heater1Setpoints.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "0"))
        item = self.Heater1Setpoints.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Time (s)"))
        item = self.Heater1Setpoints.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Setpoint (F)"))
        __sortingEnabled = self.Heater1Setpoints.isSortingEnabled()
        self.Heater1Setpoints.setSortingEnabled(False)
        item = self.Heater1Setpoints.item(0, 0)
        item.setText(_translate("MainWindow", "0"))
        self.Heater1Setpoints.setSortingEnabled(__sortingEnabled)
        self.Heater1TableAddRowButton.setText(_translate("MainWindow", "Add Row"))
        self.label.setText(_translate("MainWindow", "Heater 1 Setpoints"))
        self.label_4.setText(_translate("MainWindow", "Heater 2 Setpoints"))
        item = self.Heater2Setpoints.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "0"))
        item = self.Heater2Setpoints.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Time (s)"))
        item = self.Heater2Setpoints.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Setpoint (F)"))
        __sortingEnabled = self.Heater2Setpoints.isSortingEnabled()
        self.Heater2Setpoints.setSortingEnabled(False)
        item = self.Heater2Setpoints.item(0, 0)
        item.setText(_translate("MainWindow", "0"))
        self.Heater2Setpoints.setSortingEnabled(__sortingEnabled)
        self.label_30.setText(_translate("MainWindow", "Heater 3 Setpoints"))
        item = self.Heater3Setpoints.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "0"))
        item = self.Heater3Setpoints.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Time (s)"))
        item = self.Heater3Setpoints.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Setpoint (F)"))
        __sortingEnabled = self.Heater3Setpoints.isSortingEnabled()
        self.Heater3Setpoints.setSortingEnabled(False)
        item = self.Heater3Setpoints.item(0, 0)
        item.setText(_translate("MainWindow", "0"))
        self.Heater3Setpoints.setSortingEnabled(__sortingEnabled)
        self.Heater2TableAddRowButton.setText(_translate("MainWindow", "Add Row"))
        self.Heater3TableAddRowButton.setText(_translate("MainWindow", "Add Row"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.TabOperations), _translate("MainWindow", "Operations"))
        self.VariableT2.setText(_translate("MainWindow", "VariableT2"))
        self.LabelT2.setText(_translate("MainWindow", "LabelT2"))
        self.LabelH1.setText(_translate("MainWindow", "LabelH1"))
        self.VariablePress1.setText(_translate("MainWindow", "VariablePress1"))
        self.LabelPress4.setText(_translate("MainWindow", "LabelPress4"))
        self.LabelPump1.setText(_translate("MainWindow", "LabelPump1"))
        self.VariableT8.setText(_translate("MainWindow", "VariableT8"))
        self.LabelT6.setText(_translate("MainWindow", "LabelT6"))
        self.LabelT3.setText(_translate("MainWindow", "LabelT3"))
        self.LabelH2.setText(_translate("MainWindow", "LabelH2"))
        self.LabelT7.setText(_translate("MainWindow", "LabelT7"))
        self.LabelT8.setText(_translate("MainWindow", "LabelT8"))
        self.VariableT1.setText(_translate("MainWindow", "VariableT1"))
        self.LabelT1.setText(_translate("MainWindow", "LabelT1"))
        self.HeaderTemperature.setText(_translate("MainWindow", "Temperatures (F)"))
        self.LabelPump3.setText(_translate("MainWindow", "LabelPump3"))
        self.LabelPress3.setText(_translate("MainWindow", "LabelPress3"))
        self.VariablePress2.setText(_translate("MainWindow", "VariablePress2"))
        self.VariableT6.setText(_translate("MainWindow", "VariableT6"))
        self.LabelH3.setText(_translate("MainWindow", "LabelH3"))
        self.LabelPress1.setText(_translate("MainWindow", "LabelPress1"))
        self.VariableT3.setText(_translate("MainWindow", "VariableT3"))
        self.LabelPress2.setText(_translate("MainWindow", "LabelPress2"))
        self.VariablePress4.setText(_translate("MainWindow", "VariablePress4"))
        self.HeaderPressure.setText(_translate("MainWindow", "Pressures"))
        self.LabelT9.setText(_translate("MainWindow", "LabelT9"))
        self.LabelPump2.setText(_translate("MainWindow", "LabelPump2"))
        self.VariableT7.setText(_translate("MainWindow", "VariableT7"))
        self.VariableT4.setText(_translate("MainWindow", "VariableT4"))
        self.VariableH3.setText(_translate("MainWindow", "VariableH3"))
        self.VariablePump2.setText(_translate("MainWindow", "VaraiblePump2"))
        self.VariableH2.setText(_translate("MainWindow", "VariableH2"))
        self.VariablePress3.setText(_translate("MainWindow", "VariablePress3"))
        self.VariableT5.setText(_translate("MainWindow", "VariableT5"))
        self.VariableH1.setText(_translate("MainWindow", "VariableH1"))
        self.LabelT4.setText(_translate("MainWindow", "LabelT4"))
        self.VariablePump3.setText(_translate("MainWindow", "VariablePump3"))
        self.LabelT5.setText(_translate("MainWindow", "LabelT5"))
        self.VariablePump1.setText(_translate("MainWindow", "VariablePump1"))
        self.HeaderController.setText(_translate("MainWindow", "Controller Statuses"))
        self.VariableT9.setText(_translate("MainWindow", "VariableT9"))
        self.VariableH1SetPoint.setText(_translate("MainWindow", "SetpointH1"))
        self.VariableH2SetPoint.setText(_translate("MainWindow", "SetpointH2"))
        self.HeaderController_2.setText(_translate("MainWindow", "Controller Setpoint"))
        self.VariableH3SetPoint.setText(_translate("MainWindow", "SetpointH3"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.TabStatus), _translate("MainWindow", "Status"))
        self.VariableHeater1Temp.setText(_translate("MainWindow", "VariableHeater1Temp"))
        self.HeaderDesiredValue_2.setText(_translate("MainWindow", "Push Button"))
        self.HeaderDesiredValue.setText(_translate("MainWindow", "Desired Value \n"
"(input)"))
        self.LabelHeater1Temp.setText(_translate("MainWindow", "Temperature"))
        self.LabelHeater1MaxTemp.setText(_translate("MainWindow", "Max Temperature Allowed"))
        self.ButtonUpdateHeater1Setpoints.setText(_translate("MainWindow", "Update Heater \n"
"1 Setpoints"))
        self.LabelHeater1TSensor.setText(_translate("MainWindow", "Controlling Temperature Sensor"))
        self.VariableHeater1MaxTemp.setText(_translate("MainWindow", "VariableHeater1MaxTemp"))
        self.LabelHeaterStatus.setText(_translate("MainWindow", "Heater Status"))
        self.VariableHeater1Status.setText(_translate("MainWindow", "VariableHeater1Status"))
        self.ButtonUpdateHeater1MaxTemp.setText(_translate("MainWindow", "Update Max \n"
"Temp Setpoint"))
        self.VariableHeater1Upper.setText(_translate("MainWindow", "VariableHeater1Upper"))
        self.LabelHeater1Upper.setText(_translate("MainWindow", "Heater 1 Upper"))
        self.VariableHeater1Lower.setText(_translate("MainWindow", "VariableHeater1Lower"))
        self.LabelHeater1Lower.setText(_translate("MainWindow", "Heater 1 Lower"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.TabHeater1), _translate("MainWindow", "Heater 1"))
        self.ButtonUpdateHeater2Setpoints.setText(_translate("MainWindow", "Update Heater \n"
"2 Setpoints"))
        self.VariableHeater2Status.setText(_translate("MainWindow", "VariableHeater2Status"))
        self.LabelHeater2Status.setText(_translate("MainWindow", "Heater Status"))
        self.ButtonUpdateHeater2MaxTemp.setText(_translate("MainWindow", "Update Max \n"
"Temp Setpoint"))
        self.HeaderDesiredValue_3.setText(_translate("MainWindow", "Desired Value \n"
"(input)"))
        self.LabelHeater2MaxTemp.setText(_translate("MainWindow", "Max Temperature Allowed"))
        self.VariableHeater2Temp.setText(_translate("MainWindow", "VariableHeater2Temp"))
        self.LabelHeater2Temp.setText(_translate("MainWindow", "Temperature"))
        self.VariableHeater2MaxTemp.setText(_translate("MainWindow", "VariableHeater2MaxTemp"))
        self.HeaderDesiredValue_4.setText(_translate("MainWindow", "Push Button"))
        self.VariableHeater2Lower.setText(_translate("MainWindow", "VariableHeater2Lower"))
        self.LabelHeater2LowerName.setText(_translate("MainWindow", "Heater 2 Lower"))
        self.LabelHeater2TSensor.setText(_translate("MainWindow", "Controlling Temperature Sensor"))
        self.LabelHeater2UpperName.setText(_translate("MainWindow", "Heater 2 Upper"))
        self.VariableHeater2Upper.setText(_translate("MainWindow", "VariableHeater2Upper"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.TabHeater2), _translate("MainWindow", "Heater 2"))
        self.VariableHeater3MaxTemp.setText(_translate("MainWindow", "VariableHeater3MaxTemp"))
        self.LabelHeater3Temp.setText(_translate("MainWindow", "Temperature"))
        self.LabelHeater3Lower.setText(_translate("MainWindow", "Heater 3 Lower"))
        self.VariableHeater3Status.setText(_translate("MainWindow", "VariableHeater3Status"))
        self.HeaderDesiredValue_6.setText(_translate("MainWindow", "Push Button"))
        self.LabelHeater3MaxTemp.setText(_translate("MainWindow", "Max Temperature Allowed"))
        self.VariableHeater3Temp.setText(_translate("MainWindow", "VariableHeater3Temp"))
        self.VariableHeater3Lower.setText(_translate("MainWindow", "VariableHeater3Lower"))
        self.ButtonUpdateHeater3MaxTemp.setText(_translate("MainWindow", "Update Max \n"
"Temp Setpoint"))
        self.LabelHeater3Status.setText(_translate("MainWindow", "Heater Status"))
        self.HeaderDesiredValue_5.setText(_translate("MainWindow", "Desired Value \n"
"(input)"))
        self.ButtonUpdateHeater3Setpoints.setText(_translate("MainWindow", "Update Heater \n"
"3 Setpoints"))
        self.LabelHeater3TSensor.setText(_translate("MainWindow", "Controlling Temperature Sensor"))
        self.LabelHeater3Upper.setText(_translate("MainWindow", "Heater 3 Upper"))
        self.VariableHeater3Upper.setText(_translate("MainWindow", "VariableHeater3Upper"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.TabHeater3), _translate("MainWindow", "Heater 3"))
        self.VariablePump1Upper.setText(_translate("MainWindow", "Pump1VolUpperLimit"))
        self.label_9.setText(_translate("MainWindow", "Intercept"))
        self.label_2.setText(_translate("MainWindow", "Desired Value (Input)"))
        self.label_8.setText(_translate("MainWindow", "Slope"))
        self.VariablePump1Volume.setText(_translate("MainWindow", "Pump1Volume"))
        self.label_3.setText(_translate("MainWindow", "Push Button"))
        self.label_11.setText(_translate("MainWindow", "Volume"))
        self.VariablePump1VolSlope.setText(_translate("MainWindow", "Pump1VolSlope"))
        self.VariablePump1Pressure.setText(_translate("MainWindow", "Pump1Pressure"))
        self.label_13.setText(_translate("MainWindow", "Pressure"))
        self.LabelPump1UpperLimit.setText(_translate("MainWindow", "Volume Upper Limit (gal)"))
        self.label_6.setText(_translate("MainWindow", "Current Value"))
        self.ButtonUpdatePump1VolCalcInputs.setText(_translate("MainWindow", "Update Pump1 Vol Calc Inputs"))
        self.label_7.setText(_translate("MainWindow", "Component"))
        self.LabelPump1LowerLimit.setText(_translate("MainWindow", "Volume Lower Limit (gal)"))
        self.LabelPump1PSensor.setText(_translate("MainWindow", "Controlling Pressure Sensor:"))
        self.VariablePump1Lower.setText(_translate("MainWindow", "Pump1VolLowerLimit"))
        self.VariablePump1VolIntercept.setText(_translate("MainWindow", "Pump1VolIntercept"))
        self.ButtonUpdatePump1Setpoints.setText(_translate("MainWindow", "Update Pump 1 Setpoints"))
        self.label_31.setText(_translate("MainWindow", "Pump Status"))
        self.LabelPump1Status.setText(_translate("MainWindow", "Pump1Status"))
        self.label_15.setText(_translate("MainWindow", "Volume = Pressure (psi) * slope + intercept"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.TabPump1), _translate("MainWindow", "Pump1"))
        self.label_14.setText(_translate("MainWindow", "Push Button"))
        self.VariablePump2VolSlope.setText(_translate("MainWindow", "Pump2VolSlope"))
        self.label_12.setText(_translate("MainWindow", "Slope"))
        self.label_10.setText(_translate("MainWindow", "Intercept"))
        self.label_16.setText(_translate("MainWindow", "Volume"))
        self.VariablePump2Pressure.setText(_translate("MainWindow", "Pump2Pressure"))
        self.label_17.setText(_translate("MainWindow", "Pressure"))
        self.VariablePump2Volume.setText(_translate("MainWindow", "Pump2Volume"))
        self.label_5.setText(_translate("MainWindow", "Desired Value (Input)"))
        self.VariablePump2VolIntercept.setText(_translate("MainWindow", "Pump2VolIntercept"))
        self.label_18.setText(_translate("MainWindow", "Current Value"))
        self.LabelPump2UpperLimit.setText(_translate("MainWindow", "Volume Upper Limit (gal)"))
        self.label_19.setText(_translate("MainWindow", "Component"))
        self.LabelPump2LowerLimit.setText(_translate("MainWindow", "Volume Lower Limit (gal)"))
        self.ButtonUpdatePump2VolCalcInputs.setText(_translate("MainWindow", "Update Pump2 Vol Calc Inputs"))
        self.ButtonUpdatePump2Setpoints.setText(_translate("MainWindow", "Update Pump 2 Setpoints"))
        self.LabelPump2PSensor.setText(_translate("MainWindow", "Controlling Pressure Sensor:"))
        self.VariablePump2Upper.setText(_translate("MainWindow", "Pump2VolUpperLimit"))
        self.VariablePump2Lower.setText(_translate("MainWindow", "Pump2VolLowerLimit"))
        self.label_32.setText(_translate("MainWindow", "Pump Status"))
        self.LabelPump2Status.setText(_translate("MainWindow", "Pump2Status"))
        self.label_21.setText(_translate("MainWindow", "Volume = Pressure (psi) * slope + intercept"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.TabPump2), _translate("MainWindow", "Pump2"))
        self.label_22.setText(_translate("MainWindow", "Desired Value (Input)"))
        self.label_20.setText(_translate("MainWindow", "Intercept"))
        self.label_23.setText(_translate("MainWindow", "Slope"))
        self.VariablePump3VolSlope.setText(_translate("MainWindow", "Pump3VolSlope"))
        self.LabelPump2UpperLimit_2.setText(_translate("MainWindow", "Volume Upper Limit (gal)"))
        self.label_27.setText(_translate("MainWindow", "Current Value"))
        self.LabelPump3PSensor.setText(_translate("MainWindow", "Controlling Pressure Sensor:"))
        self.VariablePump3VolIntercept.setText(_translate("MainWindow", "Pump3VolIntercept"))
        self.label_25.setText(_translate("MainWindow", "Volume"))
        self.VariablePump3Upper.setText(_translate("MainWindow", "Pump3VolUpperLimit"))
        self.VariablePump3Lower.setText(_translate("MainWindow", "Pump3VolLowerLimit"))
        self.label_28.setText(_translate("MainWindow", "Component"))
        self.ButtonUpdatePump3VolCalcInputs.setText(_translate("MainWindow", "Update Pump3 Vol Calc Inputs"))
        self.LabelPump2LowerLimit_2.setText(_translate("MainWindow", "Volume Lower Limit (gal)"))
        self.label_24.setText(_translate("MainWindow", "Push Button"))
        self.label_26.setText(_translate("MainWindow", "Pressure"))
        self.ButtonUpdatePump3Setpoints.setText(_translate("MainWindow", "Update Pump 3 Setpoints"))
        self.VariablePump3Pressure.setText(_translate("MainWindow", "Pump3Pressure"))
        self.VariablePump3Volume.setText(_translate("MainWindow", "Pump3Volume"))
        self.label_33.setText(_translate("MainWindow", "Pump Status"))
        self.LabelPump3Status.setText(_translate("MainWindow", "Pump3Status"))
        self.label_29.setText(_translate("MainWindow", "Volume = Pressure (psi) * slope + intercept"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_2), _translate("MainWindow", "Pump3"))
        self.serialLabel.setText(_translate("MainWindow", "SerialLabel"))
        self.Button_startSerial.setText(_translate("MainWindow", "Push to Start Serial Connection"))
        self.CurrentTimeLabel.setText(_translate("MainWindow", "Current Time:"))
        self.CurrentTimeLabel_2.setText(_translate("MainWindow", "Brewing Time:"))
        self.PausePushButton.setText(_translate("MainWindow", "Pause"))
        self.menuWelcome_to_the_CCBC_Brewery.setTitle(_translate("MainWindow", "Welcome to the CCBC Brewery!"))

